"""adjusted character table

Revision ID: 0a922f7cff26
Revises: 0e0381aea318
Create Date: 2026-02-28 13:28:06.633688

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a922f7cff26"
down_revision: Union[str, Sequence[str], None] = "0e0381aea318"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("url", sa.String(length=2048), nullable=True))
    op.add_column(
        "characters", sa.Column("achievement_points", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "achievement_points")
    op.drop_column("characters", "url")
    # ### end Alembic commands ###
