"""optional locales

Revision ID: 0e0381aea318
Revises: 1d7fd99c72d4
Create Date: 2026-02-27 11:44:57.906921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e0381aea318'
down_revision: Union[str, Sequence[str], None] = '1d7fd99c72d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locale', 'locales',
               existing_type=postgresql.ENUM('EN_US', 'RU_RU', 'EN_EN', name='localesenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locale', 'locales',
               existing_type=postgresql.ENUM('EN_US', 'RU_RU', 'EN_EN', name='localesenum'),
               nullable=False)
    # ### end Alembic commands ###
