"""fill regions

Revision ID: 1d7fd99c72d4
Revises: 3f3ab6d65c51
Create Date: 2026-02-26 14:48:58.592874

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d7fd99c72d4"
down_revision: Union[str, Sequence[str], None] = "3f3ab6d65c51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""INSERT INTO region (id, region) VALUES
    (1, 'NA'),
    (2, 'EU'),
    (3, 'KR'),
    (4, 'TW')""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DELETE FROM region
                        WHERE "region" in ('NA', 'EU', 'KR', 'TW')""")
    # ### end Alembic commands ###
