"""fill locales

Revision ID: 3f3ab6d65c51
Revises: ff16e080cbbb
Create Date: 2026-02-26 14:43:39.153818

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f3ab6d65c51"
down_revision: Union[str, Sequence[str], None] = "ff16e080cbbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO locale(locales, id) VALUES
        ('EN_US', 1),
        ('RU_RU', 2),
        ('EN_EN', 3)
    """)
    # ### end Alembic commands ###


# class LocalesEnum(StrEnum):
#     EN_US = "en_US"
#     RU_RU = "ru_RU"
#     EN_EN = "en_EN"


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DELETE FROM locale WHERE locales in ('EN_US', 'RU_RU', 'EN_EN')
    """)
