"""added is_deleted column to the character and owner tables

Revision ID: a062998592f2
Revises: b69ff59c3c92
Create Date: 2026-03-01 12:54:47.545115

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a062998592f2"
down_revision: Union[str, Sequence[str], None] = "b69ff59c3c92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "owner",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("owner", "is_deleted")
    op.drop_column("characters", "is_deleted")
    # ### end Alembic commands ###
