"""added updated_at and created_at columns to the characters table

Revision ID: b69ff59c3c92
Revises: 0a922f7cff26
Create Date: 2026-02-28 16:58:55.715477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69ff59c3c92'
down_revision: Union[str, Sequence[str], None] = '0a922f7cff26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('characters', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'updated_at')
    op.drop_column('characters', 'created_at')
    # ### end Alembic commands ###
