"""added is_deleted column to characters table

Revision ID: fa23e0ff78f0
Revises: c2c620f98e98
Create Date: 2026-03-02 13:14:02.199025

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa23e0ff78f0"
down_revision: Union[str, Sequence[str], None] = "c2c620f98e98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "is_deleted")
    # ### end Alembic commands ###
