"""initial migration

Revision ID: ff16e080cbbb
Revises:
Create Date: 2026-02-26 14:43:05.109226

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff16e080cbbb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locale",
        sa.Column(
            "locales",
            sa.Enum("EN_US", "RU_RU", "EN_EN", name="localesenum"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "owner",
        sa.Column("discord_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_owner_discord_id"), "owner", ["discord_id"], unique=False)
    op.create_table(
        "realm",
        sa.Column("realm_name", sa.String(length=18), nullable=False),
        sa.Column("realm_short_name", sa.String(length=12), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("realm_name"),
        sa.UniqueConstraint("realm_short_name"),
    )
    op.create_table(
        "region",
        sa.Column(
            "region", sa.Enum("NA", "EU", "KR", "TW", name="regionenum"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("region"),
    )
    op.create_table(
        "characters",
        sa.Column("character_name", sa.String(length=20), nullable=False),
        sa.Column("realm_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["realm_id"], ["realm.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "realms_info",
        sa.Column("realm_slug_id", sa.Integer(), nullable=False),
        sa.Column("realm_region_id", sa.Integer(), nullable=False),
        sa.Column("locale_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["locale_id"], ["locale.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["realm_region_id"], ["region.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["realm_slug_id"], ["realm.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "owner_to_character",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["owner.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("owner_id", "character_id"),
        sa.UniqueConstraint("character_id"),
        sa.UniqueConstraint("character_id", name="uq_character_per_raider"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("owner_to_character")
    op.drop_table("realms_info")
    op.drop_table("characters")
    op.drop_table("region")
    op.drop_table("realm")
    op.drop_index(op.f("ix_owner_discord_id"), table_name="owner")
    op.drop_table("owner")
    op.drop_table("locale")
    # ### end Alembic commands ###
